#!/bin/bash
printf "\e[0m\n"
printf "\e[0m\e[92m  _ _ _ \e[0m\e[93m  _               _      \e[0m\n"
printf "\e[0m\e[92m |  _ _|\e[0m\e[93m (_)             | |     \e[0m\n"
printf "\e[0m\e[92m | |_   \e[0m\e[93m  _  _ _ _   ____| |          \e[0m\n"
printf "\e[0m\e[92m |  _|  \e[0m\e[93m | ||  _  | |  __  |   \e[0m\n"
printf "\e[0m\e[92m | |    \e[0m\e[93m | || | | | | |__| |    \e[0m\n"
printf "\e[0m\e[92m |_|    \e[0m\e[93m |_||_| |_| |______|     \e[0m\e[1;44m[V 1.0]\e[0m\n"

echo "---------------------------- created by dilaw ---------------------------"
echo " "
echo "----------------------------- Hello $USER ------------------------------"
echo " "

echo "--------------- write the path to find the extension --------------------"
read -p " here -> " path
echo " "
echo " "
until [ -d $path ];
	do
	echo "this path not exist -> $path "
	read -p "Write other path Example /home/ ->  " path
	echo " " 
done
	echo "located -> $path  "
	echo " "
	echo "--------------- write the extension Example 'pdf ' -----------------------"
	read -p "here -> " extension
	
	find $path -name *.$extension 2>/dev/null > $extension.txt 

	
	echo " "
	echo " -> cat $extension.txt <- "
	echo " "
	echo " -> ls here/ <- "
	echo " "
	cat $extension.txt | xargs -i cp {} here/












